SistemaVisitas/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaVisitas.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;

namespace SistemaVisitas.Controllers
{
    public class RolesController : Controller
    {
        private ApplicationDbContext context = new ApplicationDbContext();

        // GET: Roles
        [Authorize]
        public ActionResult Index()
        {
            return View(context.Roles.ToList());
        }
        [Authorize]
        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection) {

            try
            {
                context.Roles.Add(new IdentityRole()
                {


                    Name = collection["RoleName"]


                });
                context.SaveChanges();
                ViewBag.ResultMessage = "Role created successfully !";
                return View("Create");

            }
            catch {
                return View();
            }

        }

        public ActionResult Delete(string RoleName) {

            var thisRole = context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            context.SaveChanges();
            return RedirectToAction("Create");

        }

        [Authorize]
        public ActionResult ManageUsers() {

            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>
            new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;
            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RoleAddToUser(String UserName, String RoleName) {



            var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context));

            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).First();
            manager.AddToRole(user.Id, RoleName);

            ViewBag.ResultMessage = "Role created";

            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem
            {
                Value = rr.Name.ToString(),
                Text = rr.Name
            }).ToList();
            ViewBag.Roles = list;

            return View("ManageUsers");

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRoles(string UserName) {

            if (!string.IsNullOrWhiteSpace(UserName)){

                ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
                var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context));

                ViewBag.RolesForThisUser = manager.GetRoles(user.Id);


                var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem
                {

                    Value = rr.Name.ToString(),
                    Text = rr.Name
                }).ToList();
                ViewBag.Roles  = list;

            }
            return View("ManageUsers");

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRoleForUser(string UserName, string RoleName) {

            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context));
            
            if (manager.IsInRole(user.Id, RoleName))
            {
                manager.RemoveFromRole(user.Id, RoleName);
                ViewBag.ResultMessage = "Role removed from this user successfully";

            }
            else
            {
                ViewBag.ResultMessage = "This user doesnt belong to this role";
            }

            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem
            {

                Value = rr.Name.ToString(),
                Text = rr.Name
            }).ToList();
            ViewBag.Roles = list;

            return View("ManageUsers");
        }


    }
}

SistemaVisitas/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SistemaVisitas.Models;
/*using Excel = Microsoft.Office.Interop.Excel;*/


namespace SistemaVisitas.Controllers
{
    public class RoomsController : Controller
    {
        SistemaVisitasEntitites db = new SistemaVisitasEntitites();
        private ApplicationDbContext context = new ApplicationDbContext();




        static GeneratorRoomViewModel generatorWeek = new GeneratorRoomViewModel
        {

            IDGR = 0,
            NIVEL_COMBUSTIBLE = 0,
            PRUEBA_BOMBA = true,
            CONTACTOS_BATERIA = true,
            CARGADOR_BATERIA = 0,
            POSICION_BREAKERS = true,
            FUGA_ACEITE = false,
            TABLERO_G1 = true,
            TABLERO_G2 = true,
            EXTINTOR = true,
            DESAGUE_OBSTRUIDO = true,
            VALVULA_DESAGUE = true,
            NIVEL_GASOIL = 0,
            LETREROS = true,
            LIMPIEZA_GENERAL = true,
            VALVULA_TANQUES = true,
            

        };

        static TimeSpan HoraInicio;
        static UPSAViewModel uPSA;
        static UPSBViewModel uPSB;
        static EntranceRoomViewModel entranceRoom;
        static GeneratorRoomViewModel generatorRoom;
        static ServerRoomViewModel serverRoom;
        static OdcOfficeViewModel odcOffice;




        // GET: Rooms
        public ActionResult Index()
        {
            
            return View();
        }

        [Authorize]
        public ActionResult EntranceRoom()
        {
            return View();
        }
       
        [HttpPost]
        public ActionResult EntranceRoom( EntranceRoomViewModel model)
        {


            if (ModelState.IsValid)
            {
                entranceRoom = model;
                return RedirectToAction("UPSA");
            }

            else
            {

                return View();
            }
           

        }

        [Authorize]
        public ActionResult GeneratorRoom()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GeneratorRoom(GeneratorRoomViewModel model)
        {

            if (ModelState.IsValid)
            {
                generatorRoom = model;

                db.ENTRANCEROOMs.Add(entranceRoom);
                db.GENERATORROOMs.Add(generatorRoom);
                db.SERVERROOMs.Add(serverRoom);
                db.ODCOFFICEs.Add(odcOffice);
                db.UPSAs.Add(uPSA);
                db.UPSBs.Add(uPSB);
                db.SaveChanges();
                var x = DateTime.Now;

                RegistroVisitasViewModel registro = new RegistroVisitasViewModel()
                {

                    IDER = entranceRoom.IDER,
                    IDGR = generatorRoom.IDGR,
                    IDSR = serverRoom.IDSR,
                    IDODC = odcOffice.IDODC,
                    IDUPSA = uPSA.IDUPSA,
                    IDUPSB = uPSB.IDUPSB,
                    HORA_INICIO = HoraInicio,
                    HORA_FINAL = new TimeSpan(DateTime.Now.Hour, DateTime.Now.Minute, 0),
                    FECHA = DateTime.Now,
                    USERNAME = User.Identity.GetUserName()



                };

                db.SaveChanges();

                db.REGISTROVISITAS.Add(registro);

                db.SaveChanges();


                return RedirectToAction("Index", "Home");

            }

            else
            {
                return View();
            }


        }

        [Authorize]
        public ActionResult UPSA()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UPSA(UPSAViewModel model)
        {
            if ( (DateTime.Now.DayOfWeek.ToString() == DayOfWeek.Saturday.ToString()) && ((DateTime.Now.Hour >= 10) && (DateTime.Now.Hour + 1 <= 11)) )
            {

                if (ModelState.IsValid)
                {
                    uPSA = model;
                    return RedirectToAction("GeneratorRoom");
                }

                else
                {
                    return View();
                }





            }
            else {

                if (ModelState.IsValid)
                {
                    uPSA = model;

                    db.ENTRANCEROOMs.Add(entranceRoom);
                    db.GENERATORROOMs.Add(generatorWeek);
                    db.SERVERROOMs.Add(serverRoom);
                    db.ODCOFFICEs.Add(odcOffice);
                    db.UPSAs.Add(uPSA);
                    db.UPSBs.Add(uPSB);
                    db.SaveChanges();
                    var x = DateTime.Now;

                    RegistroVisitasViewModel registro = new RegistroVisitasViewModel()
                    {

                        IDER = entranceRoom.IDER,
                        IDGR = generatorWeek.IDGR, //Aqui envio el mismo ID que UPSA por que los dias normales, el generator room no se le hace visita. Cambio a ultimo momento.
                        IDSR = serverRoom.IDSR,
                        IDODC = odcOffice.IDODC,
                        IDUPSA = uPSA.IDUPSA,
                        IDUPSB = uPSB.IDUPSB,
                        HORA_INICIO = HoraInicio,
                        HORA_FINAL = new TimeSpan(DateTime.Now.Hour, DateTime.Now.Minute, 0),
                        FECHA = DateTime.Now,
                        USERNAME = User.Identity.GetUserName()



                    };

                    db.SaveChanges();

                    db.REGISTROVISITAS.Add(registro);

                    db.SaveChanges();


                    return RedirectToAction("Index", "Home");

                }

                else
                {
                    return View();
                }


            }
            
            
            
           

        }

        [Authorize]
        public ActionResult UPSB()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UPSB(UPSBViewModel model)
        {

            if (ModelState.IsValid)
            {
                uPSB = model;

                return RedirectToAction("EntranceRoom");
            }

            else
            {
                return View();
            }
         
        }

        [Authorize]
        public ActionResult ODCOffice()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ODCOffice(OdcOfficeViewModel model)
        {

            if (ModelState.IsValid)
            {
                odcOffice = model;

                return RedirectToAction("ServerRoom");
            }

            else
            {
                return View();
            }


        }

        [Authorize]
        public ActionResult ServerRoom()
        {
            HoraInicio = new TimeSpan(DateTime.Now.Hour, DateTime.Now.Minute, 0);
            
            return View();
        }

      
        public JsonResult GetDevicesPerRack(string rackName) {


            int column = 0;

            switch (rackName) {
                case "1":
                    column = 0;
                    break;
                case "2":
                    column = 1;
                    break;
                case "3":
                    column = 2;
                    break;
                case "4":
                    column = 3;
                    break;
                case "5":
                    column = 4;
                    break;
                case "11":
                    column = 5;
                    break;
                case "12":
                    column = 6;
                    break;
                case "13":
                    column = 7;
                    break;
                case "14":
                    column = 8;
                    break;
                case "15":
                    column = 9;
                    break;
                case "16A":
                    column = 10;
                    break;
                case "16B":
                    column = 11;
                    break;
                case "21":
                    column = 12;
                    break;
                case "22":
                    column = 13;
                    break;
                case "23":
                    column = 14;
                    break;
                case "24":
                    column = 15;
                    break;
                case "25A":
                    column = 16;
                    break;
                case "25B":
                    column = 17;
                    break;
                case "26A":
                    column = 18;
                    break;
                case "26B":
                    column = 19;
                    break;
                case "27":
                    column = 20;
                    break;
                case "28":
                    column = 21;
                    break;
                case "29":
                    column = 22;
                    break;
                default:
                    column = 23;
                    break;
            }


            List<string> xx = new List<string>();

            string con =
     @"Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:/Users/Junio/source/repos/SistemaVisitas/SistemaVisitas/Data/data.xls;" +
     @"Extended Properties='Excel 8.0;HDR=Yes;'";
            using (OleDbConnection connection = new OleDbConnection(con))
            {
                connection.Open();
                OleDbCommand command = new OleDbCommand("select * from [Sheet1$]", connection);
                using (OleDbDataReader dr = command.ExecuteReader())
                {
                    while (dr.Read())
                    {
                        var row1Col0 = dr[column];

SistemaVisitas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SistemaVisitas/Views/Shared/newLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">
    <!-- Title Page-->
    <title>Dashboard</title>
    <!-- Fontfaces CSS-->
    <link href="~/Contents/css/font-face.css" rel="stylesheet" media="all">
    <link href="~/Contents/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="~/Contents/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="~/Contents/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <!-- Bootstrap CSS-->
    <link href="~/Contents/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">
    <!-- Vendor CSS-->
    <link href="~/Contents/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="~/Contents/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="~/Contents/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="~/Contents/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="~/Contents/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="~/Contents/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/Contents/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">
    <!-- Main CSS-->
    <link href="~/Contents/css/theme.css" rel="stylesheet" media="all">
    <script src="~/Contents/vendor/jquery-3.2.1.min.js"></script>
</head>
<body class="animsition">
    <div class="page-wrapper">
        <!-- HEADER MOBILE-->
        <header class="header-mobile d-block d-lg-none">
            <div class="header-mobile__bar">
                <div class="container-fluid">
                    <div class="header-mobile-inner">
                        <a href="">
                            <h2>@Html.ActionLink("SMARTTOUR", "Index", "Home") </h2>
                        </a>
                        <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <nav class="navbar-mobile">
                <div class="container-fluid">
                    <ul class="navbar-mobile__list list-unstyled">


                        @if (User.IsInRole("Developer"))
                        {
                            <li class="has-sub">
                                <a class="js-arrow" href="#">
                                    <i class="fas fa-tachometer-alt"></i>Rooms
                                </a>
                                <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                                    <li>
                                        <a href="">
                                            <h2>@Html.ActionLink("Entrance Room", "EntranceRoom", "Rooms") </h2>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            <h2>@Html.ActionLink("Server Room", "ServerRoom", "Rooms") </h2>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            <h2>@Html.ActionLink("Generator Room", "GeneratorRoom", "Rooms") </h2>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            <h2>@Html.ActionLink("ODC Office ", "ODCOffice", "Rooms") </h2>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            <h2>@Html.ActionLink("UPS A", "UPSA", "Rooms") </h2>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            <h2>@Html.ActionLink("UPS B", "UPSB", "Rooms") </h2>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li>
                            <a class="js-arrow" href="@Url.Action("Index", "Home")" ">
                                <i class="fas fa-tachometer-alt"></i>Inicio
                            </a>
                        </li>
                        @if (User.IsInRole("Developer"))
                        {
                            <li>
                                <a href="@Url.Action("Stadistics", "Home")">
                                    <i class="fas fa-chart-bar"></i>Estadisticas
                                </a>
                            </li>
                        } else if (User.IsInRole("Admin"))
                        {
                            <li>
                                <a href="@Url.Action("Stadistics", "Home")">
                                    <i class="fas fa-chart-bar"></i>Estadisticas
                                </a>
                            </li>
                        }
                        @if (User.IsInRole("Developer"))
                        {
                            <li>
                                <a href="@Url.Action("Index", "Roles")">
                                    <i class="fas fa-chart-bar"></i>Control Usuarios
                                </a>
                            </li>
                        }

                    </ul>
                </div>
            </nav>
        </header>
        <!-- END HEADER MOBILE-->
        <!-- MENU SIDEBAR-->
        <aside class="menu-sidebar d-none d-lg-block">
            <div class="logo" >
                <a href="">
                    <h2>@Html.ActionLink("SMARTTOUR", "Index", "Home") </h2>
                </a>
                
            </div>
            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">
                        <li>
                            <a class="js-arrow" href="@Url.Action("Index", "Home")" ">
                                <i class="fas fa-tachometer-alt"></i>Inicio
                            </a>
                        </li>
                        @if (User.IsInRole("Developer"))
                        {
                            <li>
                                <a href="@Url.Action("Stadistics", "Home")">
                                    <i class="fas fa-chart-bar"></i>Estadisticas
                                </a>
                            </li>
                        }else if (User.IsInRole("Admin"))
                        {
                            <li>
                                <a href="@Url.Action("Stadistics", "Home")">
                                    <i class="fas fa-chart-bar"></i>Estadisticas
                                </a>
                            </li>
                        }
                        @if (User.IsInRole("Developer"))
                        {
                            <li>
                                <a href="@Url.Action("Index", "Roles")">
                                    <i class="fas fa-group"></i>Control Usuarios
                                </a>
                            </li>
                        }



                        @if (User.IsInRole("Developer"))
                        {
                            <li class="has-sub">
                                <a class="js-arrow" href="#">
                                    <i class="fas fa-desktop"></i>ROOMS
                                </a>
                                <ul class="list-unstyled navbar__sub-list js-sub-list">
                                    @*
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                                    *@
                                    <li>
                                        <a href="">
                                            <h2>@Html.ActionLink("Entrance Room", "EntranceRoom", "Rooms") </h2>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            <h2>@Html.ActionLink("Server Room", "ServerRoom", "Rooms") </h2>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            <h2>@Html.ActionLink("Generator Room", "GeneratorRoom", "Rooms") </h2>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            <h2>@Html.ActionLink("ODC Office ", "ODCOffice", "Rooms") </h2>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            <h2>@Html.ActionLink("UPS A", "UPSA", "Rooms") </h2>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            <h2>@Html.ActionLink("UPS B", "UPSB", "Rooms") </h2>
                                        </a>
                                    </li>




                                </ul>
                            </li>
                        }
                    </ul>
                </nav>
            </div>
        </aside>
        <!-- END MENU SIDEBAR-->
        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            <header class="header-desktop">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="header-wrap">
                            <form class="form-header" action="" method="POST">
                                
                            </form>
                            <div class="header-button">
                                <div class="noti-wrap">
                                    
                                  
                                </div>
                                <div class="account-wrap">
                                    @Html.Partial("newLoginPartial")
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- HEADER DESKTOP-->
            <!-- MAIN CONTENT-->
            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        @RenderBody()
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div >
                        <p>Copyright © 2024 GBM DOMINICANA. All rights reserved. <a href="">DataCenter</a>.</p>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT-->
            <!-- END PAGE CONTAINER-->
        </div>
    </div>
    <!-- Jquery JS-->
  
    <!-- Bootstrap JS-->
    <script src="~/Contents/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="~/Contents/vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- Vendor JS       -->
    <script src="~/Contents/vendor/slick/slick.min.js"></script>
    <script src="~/Contents/vendor/wow/wow.min.js"></script>
    <script src="~/Contents/vendor/animsition/animsition.min.js"></script>
    <script src="~/Contents/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <script src="~/Contents/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="~/Contents/vendor/counter-up/jquery.counterup.min.js"></script>
    <script src="~/Contents/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="~/Contents/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/Contents/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="~/Contents/vendor/select2/select2.min.js"></script>
    <!-- Main JS-->
    <script src="~/Contents/js/main.js"></script>

    @Scripts.Render("~/bundles/jquery")
   
    @RenderSection("scripts", required: false)
</body>
</html>
<!-- end document-->